### ISSUE TITLE
Clear shared_preferences based on key

### ISSUE THREAD

**Issue by jordandevogelaere** [roulljdh/encrypted_shared_preferences#13]
Hi,

Is it possible to clear a single value in shared_preferences based on the key? 

I only see a clear function which clears all key/value pairs ...

Kind regards,
Jordan

**Comment by roulljdh** [comment]
Hello, Thank you for the suggestion. I just added the `remove` function to clear a single value. You may update your package version to 3.0.1 https://pub.dev/packages/encrypted_shared_preferences/versions/3.0.1
