### ISSUE TITLE
Getting an error and a bunch of warnings while deploying on ios

### ISSUE THREAD

**Issue by sunnyagarwal008** [roulljdh/encrypted_shared_preferences#2]
I'm getting the errors below while building for iOS (I've set `platform :ios, '9.0'` in the podfile)

Launching lib/main.dart on iPhone 11 in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                            5.6s
Failed to build iOS app
Could not build the application for the simulator.
Error launching application on iPhone 11.
Error output from Xcode build:
↳
** BUILD FAILED **

Xcode's output:
↳
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:107:111: error: using '!' is not allowed here; perhaps '?' was intended?
        typealias Function = (_ data: UnsafeRawPointer, _ len: CC_LONG, _ md: UnsafeMutablePointer<UInt8>) -> UnsafeMutablePointer<UInt8>!
                                                                                                              ^                          ~
                                                                                                                                         ?
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:188:5: warning: 'public' modifier is redundant for instance method declared in a public extension
    public func MD2() -> Self {
    ^~~~~~~
    
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:198:5: warning: 'public' modifier is redundant for instance method declared in a public extension
    public func MD4() -> Self {
    ^~~~~~~
    
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:208:5: warning: 'public' modifier is redundant for instance method declared in a public extension
    public func MD5() -> Self {
    ^~~~~~~
    
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:217:5: warning: 'public' modifier is redundant for instance method declared in a public extension
    public func SHA1() -> Self {
    ^~~~~~~
    
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:226:5: warning: 'public' modifier is redundant for instance method declared in a public extension
    public func SHA224() -> Self {
    ^~~~~~~
    
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:235:5: warning: 'public' modifier is redundant for instance method declared in a public extension
    public func SHA256() -> Self {
    ^~~~~~~
    
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:244:5: warning: 'public' modifier is redundant for instance method declared in a public extension
    public func SHA384() -> Self {
    ^~~~~~~
    
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:253:5: warning: 'public' modifier is redundant for instance method declared in a public extension
    public func SHA512() -> Self {
    ^~~~~~~
    
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:330:5: warning: 'public' modifier is redundant for static method declared in a public extension
    public static func random(_ length : Int) throws -> Data {
    ^~~~~~~
    
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:432:5: warning: 'public' modifier is redundant for instance method declared in a public extension
    public func hmac(_ algorithm: HMAC.Algorithm, key: Data) -> Data {
    ^~~~~~~
    
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:453:5: warning: 'public' modifier is redundant for instance method declared in a public extension
    public func hmac(_ algorithm: HMAC.Algorithm, key: String) -> String {
    ^~~~~~~
    
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:628:5: warning: 'public' modifier is redundant for instance method declared in a public extension
    public func encrypt(_ algorithm: Cipher.Algorithm, options: Cipher.Options, key: Data, iv: Data? = nil) throws -> Data {
    ^~~~~~~
    
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:646:5: warning: 'public' modifier is redundant for instance method declared in a public extension
    public func decrypt(_ algorithm: Cipher.Algorithm, options: Cipher.Options, key: Data, iv: Data? = nil) throws -> Data {
    ^~~~~~~
    
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:745:5: warning: 'public' modifier is redundant for instance method declared in a public extension
    public func derivedKey(_ salt: Data, pseudoRandomAlgorithm: PBKDF.PseudoRandomAlgorithm, rounds: UInt32, derivedKeyLength: Int) throws -> Data {
    ^~~~~~~
    
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:760:5: warning: 'public' modifier is redundant for instance method declared in a public extension
    public func calibrate(_ saltLength: Int, pseudoRandomAlgorithm: PBKDF.PseudoRandomAlgorithm, derivedKeyLength: Int, msec : UInt32) -> UInt {
    ^~~~~~~
    
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:272:48: warning: initialization of 'UnsafePointer<UInt8>' results in a dangling pointer
        return type(of: self).init(Data(bytes: UnsafePointer<UInt8>(messageDigest), count: messageDigest.count))
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:272:69: note: implicit argument conversion from '[UInt8]' to 'UnsafePointer<UInt8>' produces a pointer valid only for the duration of the call to 'init(_:)'
        return type(of: self).init(Data(bytes: UnsafePointer<UInt8>(messageDigest), count: messageDigest.count))
                                                                    ^~~~~~~~~~~~~
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:272:69: note: use the 'withUnsafeBufferPointer' method on Array in order to explicitly convert argument to buffer pointer valid for a defined scope
        return type(of: self).init(Data(bytes: UnsafePointer<UInt8>(messageDigest), count: messageDigest.count))
                                                                    ^
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:291:28: warning: initialization of 'UnsafePointer<UInt8>' results in a dangling pointer
        return Data(bytes: UnsafePointer<UInt8>(messageDigest), count: messageDigest.count).hexString()
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:291:49: note: implicit argument conversion from '[UInt8]' to 'UnsafePointer<UInt8>' produces a pointer valid only for the duration of the call to 'init(_:)'
        return Data(bytes: UnsafePointer<UInt8>(messageDigest), count: messageDigest.count).hexString()
                                                ^~~~~~~~~~~~~
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:291:49: note: use the 'withUnsafeBufferPointer' method on Array in order to explicitly convert argument to buffer pointer valid for a defined scope
        return Data(bytes: UnsafePointer<UInt8>(messageDigest), count: messageDigest.count).hexString()
                                                ^
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:332:32: warning: initialization of 'UnsafePointer<UInt8>' results in a dangling pointer
        let data = Data(bytes: UnsafePointer<UInt8>(bytes), count: bytes.count)
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:332:53: note: implicit argument conversion from '[UInt8]' to 'UnsafePointer<UInt8>' produces a pointer valid only for the duration of the call to 'init(_:)'
        let data = Data(bytes: UnsafePointer<UInt8>(bytes), count: bytes.count)
                                                    ^~~~~
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:332:53: note: use the 'withUnsafeBufferPointer' method on Array in order to explicitly convert argument to buffer pointer valid for a defined scope
        let data = Data(bytes: UnsafePointer<UInt8>(bytes), count: bytes.count)
                                                    ^
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:436:28: warning: initialization of 'UnsafePointer<UInt8>' results in a dangling pointer
        return Data(bytes: UnsafePointer<UInt8>(result), count: result.count)
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:436:49: note: implicit argument conversion from '[UInt8]' to 'UnsafePointer<UInt8>' produces a pointer valid only for the duration of the call to 'init(_:)'
        return Data(bytes: UnsafePointer<UInt8>(result), count: result.count)
                                                ^~~~~~
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:436:49: note: use the 'withUnsafeBufferPointer' method on Array in order to explicitly convert argument to buffer pointer valid for a defined scope
        return Data(bytes: UnsafePointer<UInt8>(result), count: result.count)
                                                ^
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:592:45: warning: initialization of 'UnsafeRawPointer' results in a dangling pointer
        let ivData = self.iv == nil ? nil : UnsafeRawPointer(self.iv!)
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:592:69: note: implicit argument conversion from 'Cipher.IV' (aka 'Array<UInt8>') to 'UnsafeRawPointer' produces a pointer valid only for the duration of the call to 'init(_:)'
        let ivData = self.iv == nil ? nil : UnsafeRawPointer(self.iv!)
                                                             ~~~~~~~^
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:592:69: note: use the 'withUnsafeBytes' method on Array in order to explicitly convert argument to buffer pointer valid for a defined scope
        let ivData = self.iv == nil ? nil : UnsafeRawPointer(self.iv!)
                                                                    ^
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:631:28: warning: initialization of 'UnsafePointer<UInt8>' results in a dangling pointer
        return Data(bytes: UnsafePointer<UInt8>(encryptedBytes), count: encryptedBytes.count)
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:631:49: note: implicit argument conversion from '[UInt8]' to 'UnsafePointer<UInt8>' produces a pointer valid only for the duration of the call to 'init(_:)'
        return Data(bytes: UnsafePointer<UInt8>(encryptedBytes), count: encryptedBytes.count)
                                                ^~~~~~~~~~~~~~
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:631:49: note: use the 'withUnsafeBufferPointer' method on Array in order to explicitly convert argument to buffer pointer valid for a defined scope
        return Data(bytes: UnsafePointer<UInt8>(encryptedBytes), count: encryptedBytes.count)
                                                ^
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:649:28: warning: initialization of 'UnsafePointer<UInt8>' results in a dangling pointer
        return Data(bytes: UnsafePointer<UInt8>(decryptedBytes), count: decryptedBytes.count)
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:649:49: note: implicit argument conversion from '[UInt8]' to 'UnsafePointer<UInt8>' produces a pointer valid only for the duration of the call to 'init(_:)'
        return Data(bytes: UnsafePointer<UInt8>(decryptedBytes), count: decryptedBytes.count)
                                                ^~~~~~~~~~~~~~
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:649:49: note: use the 'withUnsafeBufferPointer' method on Array in order to explicitly convert argument to buffer pointer valid for a defined scope
        return Data(bytes: UnsafePointer<UInt8>(decryptedBytes), count: decryptedBytes.count)
                                                ^
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:747:28: warning: initialization of 'UnsafePointer<UInt8>' results in a dangling pointer
        return Data(bytes: UnsafePointer<UInt8>(key), count: key.count)
                           ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:747:49: note: implicit argument conversion from 'PBKDF.DerivedKey' (aka 'Array<UInt8>') to 'UnsafePointer<UInt8>' produces a pointer valid only for the duration of the call to 'init(_:)'
        return Data(bytes: UnsafePointer<UInt8>(key), count: key.count)
                                                ^~~
/Users/sunnyagarwal/src/stacked-example/ios/Pods/SCrypto/Source/SCrypto.swift:747:49: note: use the 'withUnsafeBufferPointer' method on Array in order to explicitly convert argument to buffer pointer valid for a defined scope
        return Data(bytes: UnsafePointer<UInt8>(key), count: key.count)
                                                ^
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')

**Comment by crushman1** [comment]
im having this same issue. i think it happened after flutter update

**Comment by roulljdh** [comment]
How about try deleting both the android and ios folder and run 'flutter create .' on the root folder. I'm guessing this might be a conflict on Swift, If that's the case then maybe lower the Swift version on the Runner project inside Xcode.

**Comment by devsherif** [comment]
I faced the same issue and fixed it.
Just open the iOS module on xCode. Try running the app, errors with fix suggestions will appear. just click the error and then click the "Fix" button. Another similar error will appear , click the error then fix.
Now you can return back to flutter and run the app successfully.
It is just a minor issue hope the owner of the repository could fix it very soon.

**Comment by roulljdh** [comment]
Hello, The 2.0.0 release just migrated its encryption library and also added support for sound null safety. This should be ok by now.
