### ISSUE TITLE
Missing reload() interface method

### ISSUE THREAD

**Issue by corto25** [roulljdh/encrypted_shared_preferences#3]
When reading and writing data from Isolates and main thread, changes made by one will not be perceived by the others. Data persisted on disk will be all writes from one of the isolates or main thread and none of the others.

While attempting to reproduce this on a smaller example, I used SharedPreferences directly without encryption and was able to reproduce the same behavior (no sharing of data between threads). However, I also found SharedPreference's reload() method and added a call to this method before reading. This solved the problem entirely.

https://pub.dev/documentation/shared_preferences/latest/shared_preferences/SharedPreferences/reload.html

A solution would be to create a new method on the EncryptedSharedPreferences interface to call reload on its internal private SharedPreferences.
Another solution could be to create a new EncryptedSharedPreferences constructor that accepts a previously and externally managed SharedPreference instance. I haven't examined how EncryptedSharedPreferences uses the SharedPreferences, so this should be allowed only if it would be safe to interact with this externally managed SharedPreferences (read/write unencrypted data in some keys) at the same time as interacting with the wrapping EncryptedSharedPreferences. Former solution is probably safest/quickest to implement.

Regards,
Simon

**Comment by roulljdh** [comment]
Hello, I looked into this and made a new release to address these issues. Check it out. 

I also added the option to pass a custom SharedPreferences instance for future proofing in case you want to use newer versions of SharedPreferences and you can now access the internal SharedPreferences instance in case you want to access its internal methods not exposed by EncryptedSharedPreferences.

**Comment by corto25** [comment]
Sorry for the long delay. I have switched my code back to use EncryptedSharedPreferences using the reload() method and it all works like a charm!  Thank you!
