### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by francis94c** [roulljdh/encrypted_shared_preferences#6]
Hi @roulljdh 

I'm currently migrating a flutter project that depends on this package, to a null safe version and i can see that this package is not null safe at the moment. 

Is it something you plan to do anytime soon or should i go ahead and make the changes?

**Comment by roulljdh** [comment]
Go ahead and make the changes.

**Comment by francis94c** [comment]
Alright, It's done but i need to do the same for Its dependent package `flutter_string_encryption` before i can open the pull request.

**Comment by viplmad** [comment]
I went ahead and forked this repo to replace `flutter_string_encryption` with `encrypt` so it's now null safe.
I've been using it internally with another project and I have found no issues so far, but I just decided to publish it as a fork recently. I leave the link if anyone wants to try it out: https://github.com/viplmad/encrypted_shared_preferences

**Comment by n00bsys0p** [comment]
I would guess that given the flutter_string_encryption package hasn't been updated in over 2 years, that it's not likely to be updated at all. `encrypt` library looks much more likely to be of high standard, being a high level wrapper round PointyCastle.

**Comment by roulljdh** [comment]
> I would guess that given the flutter_string_encryption package hasn't been updated in over 2 years, that it's not likely to be updated at all. `encrypt` library looks much more likely to be of high standard, being a high level wrapper round PointyCastle.

Alright then, @viplmad can you make a PR of your fork?

**Comment by viplmad** [comment]
Sure thing!
I just created the pull request (#7). There may be some other changes (gitignore mainly) or removal of files that I don't normally upload to source control, but I don't mind if they're reverted.

**Comment by roulljdh** [comment]
Sorry for the long overdue. I just merged @viplmad's PR and and published the changes. Update your package version to 2.0.0 in your apps to be able to use it. Thank you everyone for the support and suggestions. I appreciate it.
