### ISSUE TITLE
Unhandled Exception: Unhandled error MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

### ISSUE THREAD

**Issue by eliasjtg** [roulljdh/encrypted_shared_preferences#8]
Version: ^2.0.0

I installed too shared_preferences: ^2.0.6 and same error

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.2.3 at /Users/imac/development/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/imac/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (3 available)
    • Redmi Note 8 (mobile)  • 17eba2c2   • android-arm64  • Android 10 (API 29)
    • moto g 7 plus (mobile) • ZY225G7TW3 • android-arm64  • Android 10 (API 29)
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 92.0.4515.131

• No issues found!

```

**Comment by roulljdh** [comment]
Hello, I just published new versions of this package. But I haven't encountered this issue with that specific version of shared preferences. But If ever this issue arises again or you want to use the regular shared preferences alongside this one. 

You could always use the internal shared preferences instance of this package to do so:

```dart
SharedPreferences instance = await encryptedSharedPreferences.getInstance();
String hello = 'hello';

// This will save [hello] as plain text
await instance.setString('hello', hello);
```

**Comment by DennisMuchiri** [comment]
@roulljdh @eliasjtg I'm getting this error while using it in flutter_isolate. Please help. @eliasjtg what was your solution?

https://github.com/rmawatson/flutter_isolate/issues/106

**Comment by roulljdh** [comment]
> @roulljdh @eliasjtg I'm getting this error while using it in flutter_isolate. Please help. @eliasjtg what was your solution?
> 
> 
> 
> https://github.com/rmawatson/flutter_isolate/issues/106

May I ask what is your use case for accessing the shared prefs from a spawned isolate? Currently I don't have any platform specific behavior since it's basically just a wrapper around the regular shared prefs. So this issue is with the regular shared prefs itself, not this one. Try accessing first the regular shared preferences from a spawned isolate and see if you'll get the same error just to confirm. 

In most cases, just access the value from the main isolate and do your processing on the spawned isolate to prevent issues.

**Comment by DennisMuchiri** [comment]
@roulljdh okay...I understand, my use case is to sync online data with my offline db. My api token is stored in shared preferences and since I'm calling an end point from the isolate, I'm accessing shared prefs to retrieve the token.

**Comment by roulljdh** [comment]
> @roulljdh okay...I understand, my use case is to sync online data with my offline db. My api token is stored in shared preferences and since I'm calling an end point from the isolate, I'm accessing shared prefs to retrieve the token.

I see. Do you mind installing the regular shared prefs then try to retrieve a value from the spawned isolate just to confirm this issue if it's with the regular shared prefs itself. If it works, then the solution I could think of here is to bump the version of the internal shared prefs. I'll be happy to do so, if necessary.

**Comment by DennisMuchiri** [comment]
@roulljdh the issue is the value is available from main thread but not available from the isolate...I think this could be because the isolate is a separate environment...so the data is different in different threads. Ok let me test with shared prefs.

**Comment by DennisMuchiri** [comment]
@roulljdh After much trials I discovered you have to re-initialize the shared preferences plugin after entering isolate
Using these two plugins; add to pubspec.yaml

`  shared_preferences_ios:
  shared_preferences_android:`
  
 In your isolate function
 
 `if (Platform.isAndroid) {
    SharedPreferencesAndroid.registerWith();
  } else if (Platform.isIOS) {
    SharedPreferencesIOS.registerWith();
  }`
  
  Thanks for the help. Closing.
